version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres_docker'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=library_db

    ports:
      - "5432:5432"