version: '3'

services:

  # backend:
  #   build: back-end/
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3001:3001'
  #   command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"

  postgres:
    image: 'postgres'
    container_name: 'postgres_docker'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=library_db

    ports:
      - "5432:5432"